resources:
  - name: my_source_repo
    type: GitRepo
    configuration:
      gitProvider: myGithub
      path: RjSH1/GitRepo
      branches:
        include: master
      # buildOn:
        # commit:                false
        # pullRequestCreate:     true
       # releaseRequestCreate : true
       # test comment

pipelines:      
    - name: pipeline_gitrepo_trigger
      steps:
      - name: gitrepo_trigger_step_1
        type: Bash
        configuration:
          inputResources:
            - name: my_source_repo
 #             trigger: false
        execution:
          onExecute:
            - printenv					# A benign operation for the demo
